name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: "ðŸ“¥ Check-out"
      uses: actions/checkout@v2
    - name: "ðŸ§° Install LFTP"
      run: sudo apt-get install lftp
    - name: "ðŸ§° Install Hugo"
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 0.74.2
        extended: true
    - name: "ðŸ§° Install Node"
      uses: actions/setup-node@v1
      with:
        node-version: 8.16.x
    - name: "ðŸ§° Install Yarn"
      run: npm install -g yarn
    - name: "ðŸ§° Install asset dependencies"
      run: |
        cd assets
        yarn install
    - name: "ðŸ— Build"
      run: hugo
    - name: "ðŸš€ Deploy via SFTP"
      run: |
        mkdir lftp

        cat > lftp/key << EOL
        ${{ secrets.DEPLOY_KEY }}
        EOL

        cat > lftp/script << EOL
        set sftp:connect-program ssh -i lftp/key -l ${{ secrets.DEPLOY_USER }}
        open sftp://${{ secrets.DEPLOY_TARGET_HOST }}
        mirror -eR public ${{ secrets.DEPLOY_TARGET_PATH }}
        EOL

        lftp lftp/script
