name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: "ðŸ“¥ Check-out"
        uses: actions/checkout@v1
      - name: "ðŸ§° Install Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.66.0
          extended: true
      - name: "ðŸ§° Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: 8.16.x
      - name: "ðŸ§° Install Yarn"
        run: npm install -g yarn
      - name: "ðŸ§° Install asset dependencies"
        run: |
          cd assets
          yarn install
      - name: "ðŸ— Build"
        run: hugo
      - name: "ðŸš€ Deploy via SFTP"
        run: |
          touch deploy_key
          chmod 600 deploy_key
          echo ${{ secrets.DEPLOY_KEY }} > deploy_key
          sftp -i deploy_key Worgel@orgel-braunschweigerdom.de <<EOF
          put -r public ${{ secrets.DEPLOY_TARGET_PATH }}
          EOF
      - name: "ðŸ”„ Check Lighthouse"
        id: lighthouseCheck
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          outputDirectory: /tmp/artifacts
          urls: 'https://www.orgel-braunschweigerdom.de/'
          sha: ${{ github.sha }}
      - name: "âœ… Require Lighthouse check pass"
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minPerformanceScore: "95"
          minAccessibilityScore: "90"
          minBestPracticesScore: "80"
          minSeoScore: "85"
      - name: "ðŸ“¤ Upload Lighthouse check"
        uses: actions/upload-artifact@master
        with:
          name: "Lighthouse reports"
          path: /tmp/artifacts